### ISSUE TITLE
1 or 2 doesn't do anything.

### ISSUE THREAD

**Issue by An-Untitled-Developer** [0x978/GeoGuessr_Resolver#3] opened 2023-06-22 22:51 UTC

**Comment by 0x978** [comment] 2023-06-23 21:13
I've not been able to reproduce this, can you tell me the following?:

1) What version are you using. ( Visible next to "// @version"  at the top of the script.
2) What gamemode are you trying to use the script in.
3) Can you take a screenshot of the developer tool console when pressing 1 or 2 ingame? There should be some red error messages when you press 1 or 2, if it isn't working.

**Comment by Jasper1467** [comment] 2023-06-24 22:29
Hi, I'm having the same issue when playing MapRunner, haven't tested it in other gamemodes.
I'm using version 9.7
ScreenShot:
[https://imgur.com/a/KYT520d](https://imgur.com/a/KYT520d)

**Comment by 0x978** [comment] 2023-06-25 14:52
I've looked at country streaks and not had an issue, which is strange. Can you confirm if it doesn't work in singleplayer, classic, country streaks?


However, MapRunner doesn't work so I'll fix that asap

**Comment by Jasper1467** [comment] 2023-06-25 19:43
2, 3 and 4 work for me in singleplayer, classic and country streaks. 1 Doesn't work in any gamemode for me.

**Comment by 0x978** [comment] 2023-06-26 18:26
> 2, 3 and 4 work for me in singleplayer, classic and country streaks. 1 Doesn't work in any gamemode for me.

I've still not been able to reproduce 1 not working in the listed gamemodes, this really shouldn't be possible since 1 and 2 are calling the same function.

A new, very early and buggy, version of the script is available on GitHub (but not on greasyfork), which I will also link below. Can you try this version for me? If it doesn't work can you screenshot the console?

In this version, I believe I fixed the problem with maprunner but damn it took an insane amount of work compared to other gamemodes, and will even crash the browser in maprunner if the marker is not moved before submitting the guess. (hence why it's not on greasyfork). I think the Geoguessr devs are putting more effort into hiding options for me to hook into to run the features of the script.

 https://raw.githubusercontent.com/0x978/GeoGuessr_Resolver/master/Resolver.js

**Comment by Jasper1467** [comment] 2023-06-26 19:28
I checked again with the link you provided and still didn't work, however I got it fixed by switching to a different userscript manager. It didn't work with Violent Monkey, but it does with Tamper Monkey. So I guess it's a problem with Violent Monkey.

**Closed** 2023-06-28 19:34 UTC
